# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'
  name: 'self-host'


variables:
  buildConfiguration: 'Release'
  solutionPath: 'Lab4_ClassLibrary.sln' 
  feedId: 'https://pkgs.dev.azure.com/smunozgo/b4bcea45-b686-4897-864a-da46933c130a/_packaging/Lab4-Feed/nuget/v3/index.json'  

steps:
  # Checkout the GitHub repo connected to this pipeline
  - checkout: self

  # Install .NET 8 SDK
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '8.0.x'
    displayName: 'Install .NET 8 SDK'

  # Authenticate with Azure Artifacts 
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate to Azure Artifacts'

  # Restore NuGet packages for the entire solution
  - script: dotnet restore $(solutionPath)
    displayName: 'Restore dependencies'

  # Build the entire solution
  - script: dotnet build $(solutionPath) --configuration $(buildConfiguration) --no-restore
    displayName: 'Build solution'

  # Pack the solution into a NuGet package 
  - script: dotnet pack $(solutionPath) --configuration $(buildConfiguration) --no-build -o "$(Build.ArtifactStagingDirectory)"
    displayName: 'Pack NuGet package'

  # Push the NuGet package to Azure Artifacts
  - task: NuGetCommand@2
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      publishVstsFeed: $(feedId)
    displayName: 'Push package to Azure Artifacts'